name: Deploy Swagger UI to Pages

on:
  push:
    branches:
      - main
    paths:
      - spec/**
      - .github/workflows/deploy_swagger_ui_to_pages.yaml
      - .github/workflows/script/create-swagger-ui-pages.sh
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout swagger-ui
        uses: actions/checkout@v3
        with:
          repository: swagger-api/swagger-ui
          ref: 'v4.15.5'
          path: swagger-ui
      - name: Create Swagger UI Pages
        run: |
          chmod +x main/.github/workflows/script/create-swagger-ui-pages.sh
          ./main/.github/workflows/script/create-swagger-ui-pages.sh
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'main/docs/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1